name: EAS Production Build

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install EAS CLI
      run: npm install -g eas-cli
    
    - name: Setup Android Keystore
      run: |
        mkdir -p credentials/android
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > credentials/android/keystore.jks
        echo "${{ secrets.CREDENTIALS_JSON_BASE64 }}" | base64 -d > credentials.json
    
    - name: Configure EAS
      run: eas build:configure --platform all
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    - name: Build Android Production
      id: android-build
      run: |
        echo "Starting Android build..."
        BUILD_RESPONSE=$(eas build --platform android --profile production --non-interactive --json)
        echo "Build response: $BUILD_RESPONSE"
        BUILD_ID=$(echo "$BUILD_RESPONSE" | jq -r '.id')
        echo "Extracted build ID: $BUILD_ID"
        echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
        echo "Waiting for Android build to complete..."
        eas build:wait --id $BUILD_ID
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    - name: Download Android Artifact
      run: |
        BUILD_ID=${{ steps.android-build.outputs.build_id }}
        eas build:download --id $BUILD_ID --output android-build.apk
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    - name: Upload Android Artifact to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: android-build.apk
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Android Artifact to Workflow
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: android-build.apk
    
    # - name: Build iOS Production
    #   id: ios-build
    #   run: |
    #     BUILD_ID=$(eas build --platform ios --profile production --non-interactive --json | jq -r '.id')
    #     echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
    #     echo "Waiting for iOS build to complete..."
    #     eas build:wait --id $BUILD_ID
    #   env:
    #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    # - name: Download iOS Artifact
    #   run: |
    #     BUILD_ID=${{ steps.ios-build.outputs.build_id }}
    #     eas build:download --id $BUILD_ID --output ios-build.ipa
    #   env:
    #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    # - name: Upload iOS Artifact to Release
    #   if: github.event_name == 'release'
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: ios-build.ipa
    #     token: ${{ secrets.GITHUB_TOKEN }}
        
    # - name: Upload iOS Artifact to Workflow
    #   if: github.event_name == 'push'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ios-build
    #     path: ios-build.ipa 