name: EAS Production Build

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install EAS CLI
      run: npm install -g eas-cli
    
    - name: Setup Android Keystore
      run: |
        mkdir -p credentials/android
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > credentials/android/keystore.jks
        echo "${{ secrets.CREDENTIALS_JSON_BASE64 }}" | base64 -d > credentials.json
    
    - name: Configure EAS
      run: eas build:configure --platform all
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    - name: Build Android Production
      id: android-build
      run: |
        echo "Starting Android build..."
        BUILD_RESPONSE=$(eas build --platform android --profile production --non-interactive --json)
        echo "Build response: $BUILD_RESPONSE"
        BUILD_ID=$(echo "$BUILD_RESPONSE" | jq -r '.[0].id')
        BUILD_URL=$(echo "$BUILD_RESPONSE" | jq -r '.[0].artifacts.buildUrl')
        echo "Extracted build ID: $BUILD_ID"
        echo "Extracted build URL: $BUILD_URL"
        echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
        echo "build_url=$BUILD_URL" >> $GITHUB_OUTPUT
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    - name: Download Android Artifact
      run: |
        BUILD_URL=${{ steps.android-build.outputs.build_url }}
        curl -L "$BUILD_URL" -o android-build.aab
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Convert AAB to APK
      run: |
        # Download bundletool
        curl -L "https://github.com/google/bundletool/releases/download/1.18.1/bundletool-all-1.18.1.jar" -o bundletool.jar
        
        # Convert AAB to APK
        java -jar bundletool.jar build-apks --bundle=android-build.aab --output=android-build.apks --mode=universal
        
        # Extract the APK from the APKS file (it's just a zip)
        unzip -p android-build.apks universal.apk > android-build.apk
    
    - name: Upload Android Artifact to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          android-build.apk
          android-build.aab
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Android Artifact to Workflow
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: android-builds
        path: |
          android-build.apk
          android-build.aab
    
    # - name: Build iOS Production
    #   id: ios-build
    #   run: |
    #     echo "Starting iOS build..."
    #     BUILD_RESPONSE=$(eas build --platform ios --profile production --non-interactive --json)
    #     echo "Build response: $BUILD_RESPONSE"
    #     BUILD_ID=$(echo "$BUILD_RESPONSE" | jq -r '.[0].id')
    #     BUILD_URL=$(echo "$BUILD_RESPONSE" | jq -r '.[0].artifacts.buildUrl')
    #     echo "Extracted build ID: $BUILD_ID"
    #     echo "Extracted build URL: $BUILD_URL"
    #     echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
    #     echo "build_url=$BUILD_URL" >> $GITHUB_OUTPUT
    #   env:
    #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    # - name: Download iOS Artifact
    #   run: |
    #     BUILD_URL=${{ steps.ios-build.outputs.build_url }}
    #     curl -L "$BUILD_URL" -o ios-build.ipa
    #   env:
    #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    # - name: Upload iOS Artifact to Release
    #   if: github.event_name == 'release'
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: ios-build.ipa
    #     token: ${{ secrets.GITHUB_TOKEN }}
        
    # - name: Upload iOS Artifact to Workflow
    #   if: github.event_name == 'push'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ios-build
    #     path: ios-build.ipa 